version: '3.7'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_tutorial
    restart: always
    ports:
      - "5678:5678"
    env_file:
      - .env
    environment:
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_BASIC_AUTH_ACTIVE=false
      - WEBHOOK_URL=http://localhost:5678/
      - N8N_RUNNERS_ENABLED=true
    volumes:
      - ./n8n-data:/home/node/.n8n
      - ./workflows:/home/node/.n8n/init-data/workflows

volumes:
  n8n-data:

# Optional: Define the network
# networks:
#   n8n-network:
#     driver: bridge 